title: welcome to X & G
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#


baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 韦小宝 # add your name
author-img: weixiaobao.jpg # add your photo
about-author: 我是一个专注于前端开发的web开发人员。总是渴望不断学习前端技术，不断提升我的专业技能。 # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: artemsheludko # add your Github handle
linkedin: # add your Linkedin handle
email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--excerpt-->
plugins:
  - jekyll-paginate
# 分页
#permalink: /:year/:month/:day/:title.html
permalink: /:year/:month/:day/:title
paginate: 6
paginate_path: "/article/:num"
#paginate: 8
#paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]

collections:
 common:
  output: true
  permalink: /:collection/:title
 ui:
  output: true
  permalink: /:collection/:title